trigger:
- main

pool: 
    name: SahiAgent



steps:
    
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
  continueOnError: true
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:/sahi_pro/userdata/sahi_reports'
    ArtifactName: 'Sahi HTML Reports'
    publishLocation: 'Container'